#filegroup(
#    name = "hand_tracking_gpu",
#    srcs = ["hand_tracking_gpu.pbtxt"],
#    visibility = ["//visibility:public"],
#)

filegroup(
    name = "hand_tracking_desktop_live",
    srcs = ["hand_tracking_desktop_live.pbtxt"],
    visibility = ["//visibility:public"],
)

exports_files(["hand_tracking_desktop_live.pbtxt"], visibility = ["//visibility:public"])

