filegroup(
    name = "hand_tracking_gpu.pbtxt",
    srcs = ["hand_tracking_gpu.pbtxt"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "hand_tracking_gpu",
    hdrs = [],
    visibility = ["//visibility:public"],
)
